### ISSUE TITLE
Shared object can't be loaded via the classloader on Android

### ISSUE THREAD

**Issue by benagastov** [ngrok/ngrok-java#50]
Good afternoon. I tried to implement Ngrok in my Android Studio Project using Java-gradle to compile. But everytime I tried to run the app, it will return com.ngrok.NativeSession error due to no implementation.

`No implementation found for com.ngrok.NativeSession com.ngrok.NativeSession.connectNative(com.ngrok.Session$Builder) (tried Java_com_ngrok_NativeSession_connectNative and Java_com_ngrok_NativeSession_connectNative__Lcom_ngrok_Session_00024Builder_2)
FATAL EXCEPTION: Thread-2
Process: com.example.ngrokjava, PID: 20169
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: No implementation found for com.ngrok.NativeSession com.ngrok.NativeSession.connectNative(com.ngrok.Session$Builder) (tried Java_com_ngrok_NativeSession_connectNative and Java_com_ngrok_NativeSession_connectNative__Lcom_ngrok_Session_00024Builder_2)
	at com.ngrok.Session.connect(Session.java:53)
	at com.ngrok.Session$Builder.connect(Session.java:542)
	at com.example.ngrokjava.MainActivity.runNgrok(MainActivity.java:47)
	at com.example.ngrokjava.MainActivity.lambda$onCreate$0(MainActivity.java:28)
	at com.example.ngrokjava.MainActivity.$r8$lambda$nPniPBgeArslOcKEjZ1t1UsHRUk(Unknown Source:0)
	at com.example.ngrokjava.MainActivity$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for com.ngrok.NativeSession com.ngrok.NativeSession.connectNative(com.ngrok.Session$Builder) (tried Java_com_ngrok_NativeSession_connectNative and Java_com_ngrok_NativeSession_connectNative__Lcom_ngrok_Session_00024Builder_2)
	at com.ngrok.NativeSession.connectNative(Native Method)
	at com.ngrok.NativeSession.connect(NativeSession.java:45)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.ngrok.Session.connect(Session.java:47)
	at com.ngrok.Session$Builder.connect(Session.java:542) 
	at com.example.ngrokjava.MainActivity.runNgrok(MainActivity.java:47) 
	at com.example.ngrokjava.MainActivity.lambda$onCreate$0(MainActivity.java:28) 
	at com.example.ngrokjava.MainActivity.$r8$lambda$nPniPBgeArslOcKEjZ1t1UsHRUk(Unknown Source:0) 
	at com.example.ngrokjava.MainActivity$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
	at java.lang.Thread.run(Thread.java:920) 
`

Edit @jrobsonchase:

Co-opting this issue for the root cause of the problem.

In `com.ngrok.Runtime`, we're using the classloader to pull the shared object out of the jar:

https://github.com/ngrok/ngrok-java/blob/d5de5815426b52fc90dc0aa54c8ff013d2f61061/ngrok-java-native/src/main/java/com/ngrok/Runtime.java#L53-L79

However, the result of the `Runtime.class.getResourceAsStream` call is `null` on Android. For some reason, extracting the shared object in this manner fails while getting the `native.properties` in `com.ngrok.NativeSession` works _just fine_. Maybe the android build process is filtering things out of the jar? We either need to find a way to fix this approach, or find a different one that we can recommend to our android-developing friends.

**Comment by nikolay-ngrok** [comment]
Hello @benagastov, this looks like a problem with your dependencies. Can you share part of your gradle configuration that adds `ngrok-java` as a dependency? You'll need to include the correct [ngrok-java-native](https://github.com/ngrok/ngrok-java/tree/main/ngrok-java-native) for your platform.

**Comment by benagastov** [comment]
Pardon me for my late response. Here is my gradle code in Android Studio:
```plugins {
    alias(libs.plugins.android.application)
    id("com.google.osdetector").version("1.7.3")
}

android {
    namespace 'com.example.ngrokjava'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.ngrokjava"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {

    implementation libs.appcompat
    implementation("com.ngrok:ngrok-java:0.4.0")
    implementation("com.ngrok:ngrok-java-native:0.4.0:linux-android-arm64-v8a")
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}```

My Main Activity java class:
```package com.example.ngrokjava;

import android.os.Bundle;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.ngrok.Session;
import com.ngrok.Http;

import java.io.IOException;
import java.nio.ByteBuffer;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_main);

        // Call ngrok execution after ViewCompat setup
        new Thread(() -> {
            try {
                runNgrok();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();

        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });
    }

    private void runNgrok() throws IOException {
        // Session.withAuthtokenFromEnv() will create a new session builder, pulling NGROK_AUTHTOKEN env variable.
        // You can get your authtoken by registering at https://dashboard.ngrok.com
        var sessionBuilder = Session.withAuthtokenFromEnv().metadata("my session");
        // Session.Builder let you customize different aspects of the session, see docs for details.
        // After customizing the builder, you connect:
        try (var session = sessionBuilder.connect()) {
            // Creates and configures http listener that will be using oauth to secure it
            var listenerBuilder = session.httpEndpoint().metadata("my listener")
                    .oauthOptions(new Http.OAuth("google"));
            // Now start listening with the above configuration
            try (var listener = listenerBuilder.listen()) {
                System.out.println("ngrok url: " + listener.getUrl());
                var buf = ByteBuffer.allocateDirect(1024);

                while (true) {
                    // Accept a new connection
                    var conn = listener.accept();

                    // Read from the connection
                    conn.read(buf);

                    System.out.println(buf.asCharBuffer());

                    // Or write to it
                    conn.write(buf);
                }
            }
        }
    }
}
```

**Comment by nikolay-ngrok** [comment]
One thing I noticed in your gradle script is using a target we don't produce:
```
implementation("com.ngrok:ngrok-java-native:0.4.0:linux-android-arm64-v8a")
```

You should probably try the one we have:
```
implementation("com.ngrok:ngrok-java-native:0.4.0:linux-android-aarch_64")
```

Also, the latest version of the sdk is `1.0.1`, so maybe you could try that (as opposed to using `0.4.0`) 👍

**Comment by SaeedRe** [comment]
@benagastov Did you fix this issue?

I had the same problem. After searching online, I found a solution: load the native library using the following code:

```
System.loadLibrary("ngrok_java")
```

After this, the error "No implementation found for com.ngrok.NativeSession" no longer appears. 
However, I encountered another crash.
```
java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/~~ymvCDlJkZUFYRKr4zK8sVA==/org.example.aoc-Zw4AZ3HIsPDyBRjKbwPvFQ==/base.apk!/lib/arm64-v8a/libngrok_java.so": 65544
at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
at java.lang.Runtime.loadLibrary0(Runtime.java:998)
at java.lang.System.loadLibrary(System.java:1661)
at org.example.aoc.AndroidNgrok.<init>(AndroidNgrok.kt:22)
at org.example.aoc.ComposableSingletons$AppKt$lambda-4$1.invoke(App.kt:17)
at org.example.aoc.ComposableSingletons$AppKt$lambda-4$1.invoke(App.kt:16)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:23)
at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:82)
at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:81)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:396)
at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:72)
at org.example.aoc.AppKt.App(App.kt:16)
at org.example.aoc.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:14)
at org.example.aoc.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:13)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:186)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:139)
2024-08-12 14:14:54.819  6779-6779  AndroidRuntime          org.example.aoc                     E  	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:138) (Ask Gemini)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:138)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:123)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:123)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)
at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1289)
at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:114)
at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:164)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:121)
at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)
at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1364)
at android.view.View.dispatchAttachedToWindow(View.java:21291)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2771)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
at android.view.Choreographer.doCallbacks(Choreographer.java:899)
at android.view.Choreographer.doFrame(Choreographer.java:832)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by diegorondini** [comment]
Hi @jrobsonchase 

I think the `SONAME` note is more relevant to this issue as this article reports:
> Each ELF shared object (“native library”) must have a SONAME (Shared Object Name) attribute. The NDK toolchain adds this attribute by default, so its absence indicates either a misconfigured alternative toolchain or a misconfiguration in your build system. A missing SONAME may lead to runtime issues such as the wrong library being loaded: the filename is used instead when this attribute is missing.

https://android-developers.googleblog.com/2016/06/android-changes-for-ndk-developers.html

```
$ $ANDROID_HOME/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/aarch64-linux-android/bin/readelf --dynamic libngrok_java.so | grep SONAME
<empty output>
```
```
$ $ANDROID_HOME/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/aarch64-linux-android/bin/readelf --dynamic libngrok_java.so 

Dynamic section at offset 0x58d548 contains 24 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x0000000000000007 (RELA)               0x1d28
 0x0000000000000008 (RELASZ)             333816 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          13907
 0x0000000000000017 (JMPREL)             0x53520
 0x0000000000000002 (PLTRELSZ)           1920 (bytes)
 0x0000000000000003 (PLTGOT)             0x58fbb0
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000006 (SYMTAB)             0x308
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x1404
 0x000000000000000a (STRSZ)              2333 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0xf48
 0x0000000000000004 (HASH)               0x104c
 0x000000000000001a (FINI_ARRAY)         0x58f538
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x000000006ffffff0 (VERSYM)             0xe18
 0x000000006ffffffe (VERNEED)            0xf04
 0x000000006fffffff (VERNEEDNUM)         2
 0x0000000000000000 (NULL)               0x0
```

**Comment by jrobsonchase** [comment]
That attribute is indeed missing, but it doesn't seem to change the loadability of the `.so` from the jar. Even with it, I still see `Runtime.class.getResourceAsStream('/libngrok_java.so')` returning `null`. Either this isn't a valid approach to packaging the `.so` on android or something else is wrong with it.

**Comment by SaeedRe** [comment]
@jrobsonchase On the Android platform, native binaries for each architecture should be placed in their corresponding `directory under src/main/jniLibs/*`.
When loading the binaries in code, simply use: ```System.loadLibrary("ngrok_java");```
By applying this fix, the library successfully worked on Android.
You can see our fix in this fork:
https://github.com/Kynetics/ngrok-java/commit/7f0788c20a09a16437b8ae35b5e91b2b92bc8a51

**Comment by jrobsonchase** [comment]
> On the Android platform, native binaries for each architecture should be placed in their corresponding directory under `src/main/jniLibs/*`

Yeah, ideally that wouldn't be necessary though - the native binary would be sourced from the jar as with "normal" java applications. Maybe there needs to be an extra build-time step that extracts it to the correct place for android automatically?

>  By applying this fix, the library successfully worked on Android.

That's great to hear! Did it completely work, or did you just get the library to load successfully? On my last android attempt, I could load the library, but the session never connected for some reason I couldn't quite determine.

**Comment by SaeedRe** [comment]
@jrobsonchase Yes, we were able to use the library to start a TCP session.
